catalog:
  '@commitlint/cli': 20.5.0
  '@commitlint/config-conventional': 20.5.0
  '@eslint/js': 10.0.1
  '@eslint/json': 1.2.0
  '@eslint/markdown': 7.5.1
  '@ianvs/prettier-plugin-sort-imports': 4.7.1
  '@iconify-json/heroicons': 1.2.3
  '@iconify-json/hugeicons': 1.2.24
  '@iconify-json/lucide': 1.2.99
  '@iconify-json/simple-icons': 1.2.75
  '@nuxt/content': 3.12.0
  '@nuxt/eslint': 1.15.2
  '@nuxt/image': 2.0.0
  '@nuxt/ui': 4.6.0
  '@nuxthub/core': 0.10.7
  '@nuxtjs/eslint-module': 4.1.0
  '@nuxtjs/plausible': 3.0.2
  '@nuxtjs/robots': 5.7.1
  '@pinia/nuxt': 0.11.3
  '@semantic-release/changelog': 6.0.3
  '@semantic-release/commit-analyzer': 13.0.1
  '@semantic-release/git': 10.0.1
  '@semantic-release/github': 12.0.6
  '@semantic-release/npm': 13.1.5
  '@semantic-release/release-notes-generator': 14.1.0
  '@tailwindcss/typography': 0.5.19
  '@tiptap/html': 3.20.5
  '@tiptap/markdown': 3.20.5
  '@tiptap/starter-kit': 3.20.5
  '@types/node': 25.5.0
  '@vueuse/core': 14.2.1
  '@vueuse/nuxt': 14.2.1
  better-sqlite3: 12.8.0
  defu: 6.1.4
  eslint: 9.39.2
  eslint-config-prettier: 10.1.8
  fuse.js: 7.1.0
  husky: 9.1.7
  jspdf: 4.2.1
  minimark: 1.0.0
  nuxt: 4.4.2
  nuxt-llms: 0.2.0
  nuxt-site-config: 3.2.21
  nuxt-studio: 1.5.1
  ofetch: 1.5.1
  openai: 6.33.0
  pinia: 3.0.4
  pinia-plugin-persistedstate: 4.7.1
  prettier: 3.8.1
  prettier-plugin-mdc: 0.2.1
  prettier-plugin-tailwindcss: 0.7.2
  semantic-release: 25.0.3
  tailwindcss: 4.2.2
  typescript: 5.9.3
  ufo: 1.6.3
  vue-tsc: 3.2.6
  wrangler: 4.77.0
  zod: 4.3.6

catalogMode: 'strict'
cleanupUnusedCatalogs: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
  - sharp
saveExact: true
shamefullyHoist: true
