export { createCommentBlockMap, drawAuditSectionItem, renderAuditSection } from './sections/audit'
export { drawAverageCard, getScoreColorKey, renderAveragesSection } from './sections/averages'
export { renderCoverPage } from './sections/cover'
export { renderReportDocument } from './sections/document'
export { renderIntroductionPage } from './sections/introduction'
export { renderNotesSection } from './sections/notes'
