name: Code Quality

on:
  workflow_call:
    inputs:
      build-command:
        description: 'Build command to run before typechecking'
        required: false
        type: string
      build-before-lint:
        description: 'Whether to build before linting'
        required: false
        default: false
        type: boolean
      lint-command:
        description: 'Lint command to run instead of default'
        required: false
        default: pnpm lint
        type: string
      build-before-typecheck:
        description: 'Whether to build before typechecking'
        required: false
        default: false
        type: boolean
      typecheck-command:
        description: 'Typecheck command to run instead of default'
        required: false
        default: pnpm typecheck
        type: string
      build-before-test:
        description: 'Whether to build before testing'
        required: false
        default: false
        type: boolean
      test-command:
        description: 'Test command to run instead of default'
        required: false
        default: pnpm test:unit
        type: string
      coverage-command:
        description: 'Coverage command to run instead of default'
        required: false
        default: pnpm test:coverage
        type: string
      runner:
        description: 'Runner to execute the job on'
        required: false
        default: ubuntu-latest
        type: string
    secrets:
      GH_PACKAGES_TOKEN:
        description: 'GitHub Packages token for installing private packages.'

jobs:
  lint:
    runs-on: ${{ inputs.runner }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup node, pnpm, GitHub packages authentication and install dependencies
        uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build packages before linting
        if: ${{ inputs.build-command && inputs.build-before-lint }}
        run: ${{ inputs.build-command }}

      - name: Lint
        run: ${{ inputs.lint-command }}

  typecheck:
    runs-on: ${{ inputs.runner }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup node, pnpm, GitHub packages authentication and install dependencies
        uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build packages before typechecking
        if: ${{ inputs.build-command && inputs.build-before-typecheck }}
        run: ${{ inputs.build-command }}

      - name: Typecheck
        run: ${{ inputs.typecheck-command }}

  test:
    runs-on: ${{ inputs.runner }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup node, pnpm, GitHub packages authentication and install dependencies
        uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build packages before testing
        if: ${{ inputs.build-command && inputs.build-before-test }}
        run: ${{ inputs.build-command }}

      - name: Test
        run: ${{ inputs.test-command }}

      - name: Coverage
        run: ${{ inputs.coverage-command }}

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: coverage
          if-no-files-found: ignore
