name: Pull Request

on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [retrigger-workflows]

permissions:
  id-token: write
  contents: read
  deployments: write
  issues: write
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    if:
      ${{ github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'content' }}
    uses: ./.github/workflows/code_quality.yml
    with:
      runner: blacksmith-4vcpu-ubuntu-2404
      build-command: pnpm nuxt:prepare
      build-before-lint: true
      build-before-typecheck: false
      build-before-test: false
      typecheck-command: pnpm typecheck
      lint-command: pnpm lint
      test-command: pnpm test:unit
      coverage-command: pnpm test:coverage
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  preview-deployment:
    if:
      ${{ github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'content' }}
    needs: code-quality
    uses: ./.github/workflows/deploy_worker.yml
    with:
      runner: blacksmith-8vcpu-ubuntu-2404
      environment: preview
      upload_version: true
    secrets: inherit
